### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by elbakouchi** [KazanExpress/mantha#2]
Hi!
Got this for my first attempt to run yarn dev

```
mantha\.webpack.config\webpack.base.ts:229
            test: chunk => ( chunkSplitPatterns.every( p => !p.test(chunk.userRequest) && !p.test( chunk._chunks.values().next().value.name )  )),
                                                ^
TypeError: Cannot read property 'name' of undefined
    at \projects\mantha\.webpack.config\webpack.base.ts:229:135
    at Array.every (<anonymous>)
    at test (\projects\mantha\.webpack.config\webpack.base.ts:229:49)
    at Function.checkTest (\projects\mantha\node_modules\webpack\lib\optimize\SplitChunksPlugin.js:220:42)
    at Object.fn [as getCacheGroups] (\projects\mantha\node_modules\webpack\lib\optimize\SplitChunksPlugin.js:188:35)
    at \projects\mantha\node_modules\webpack\lib\optimize\SplitChunksPlugin.js:283:38
    at SyncBailHook.eval (eval at create (\projects\mantha\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:16)
    at SyncBailHook.lazyCompileHook (\projects\mantha\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.seal (\projects\mantha\node_modules\webpack\lib\Compilation.js:882:38)
    at \projects\mantha\node_modules\webpack\lib\Compiler.js:479:17
    at _done (eval at create (\projects\mantha\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (C:\hamza\projects\mantha\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:32:22)
    at C:\hamza\projects\mantha\node_modules\webpack\lib\Compilation.js:756:12
    at C:\hamza\projects\mantha\node_modules\webpack\lib\Compilation.js:695:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Raiondesu** [comment]
Hello, @elbakouchi. We couldn't reproduce your bug. Could you please provide a repo which reproduces the issue?

**Comment by elbakouchi** [comment]
https://github.com/elbakouchi/mantha-bug

**Comment by Raiondesu** [comment]
@elbakouchi, unfortunately, current implementation needs the `module` options in `src/tsconfig.json` to be set to `"esnext"`. You have set it to `"commonjs"`, which has broke things.

If you change it back to `"esnext"` - the problem should not persist.

Reason:
Current environment relies heavily on the fact that components are split into async chunks using the async `import()` function and webpack's `optimization` options (with chunk splitting). Without the `"esnext"` option in `tsconfig`, the whole thing is pretty much useless.
